### ISSUE TITLE
No contract for communication with the zone editor was found on the rendered page.

### ISSUE THREAD

**Issue by alexmloy** [Sitefinity/angular-standalone-renderer#7]
hi.
after creating a template, and going to select a widget I got this message:
`No contract for communication with the zone editor was found on the rendered page.`

and in the console i got this:
```
GET http://localhost:58289/styles.ef46db3751d8e999.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:58289/runtime.6a9ae211c5621779.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:58289/main.88ce3c915b5c1500.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:58289/polyfills.0b090f6bcb5eabc6.js net::ERR_ABORTED 404 (Not Found)
```

how can i solve this?

**Comment by Gebov** [comment]
Hello,

In the output index.html file, please make sure the files have the following URL prefixes:
<script src="/sitefinity/public/renderers/angular/runtime.4b0eeb47633398848f65.js" defer></script>
<script src="/sitefinity/public/renderers/angular/polyfills.8592889c0e7a5a282dfd.js" defer></script>
<script src="/sitefinity/public/renderers/angular/scripts.034dc4a9f158d5f4b48b.js" defer></script>
<script src="/sitefinity/public/renderers/angular/main.9131e15c35657a83a559.js" defer></script>

This is controlled through the angular.json file
